// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Game on SteamGridDB.
 */
export type ArtGame = { 
/**
 * Game number on SteamGridDB.
 */
id: number, 
/**
 * Title.
 */
name: string, 
/**
 * Release year, if known.
 */
year: number | null, };
