// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Square cover on SteamGridDB.
 */
export type ArtImage = { 
/**
 * Cover number.
 */
id: number, 
/**
 * URL of the full-size image.
 */
url: string, 
/**
 * URL of the thumbnail for the list.
 */
thumb: string, 
/**
 * Width, if the service reported it.
 */
width: number | null, 
/**
 * Height, if the service reported it.
 */
height: number | null, };
