// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugSettings } from "./DebugSettings";
import type { GraphicsSettings } from "./GraphicsSettings";
import type { InputSettings } from "./InputSettings";
import type { SystemSettings } from "./SystemSettings";

/**
 * All Autorun runtime settings that Carafe puts into the NSP.
 *
 * The defaults match Autorun's behavior when there is no settings file.
 */
export type AutorunSettings = { 
/**
 * Input and key mapping.
 */
input: InputSettings, 
/**
 * Image output.
 */
graphics: GraphicsSettings, 
/**
 * CPU, synchronization, windows.
 */
system: SystemSettings, 
/**
 * Debugging.
 */
debug: DebugSettings, };
