// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SwitchButton } from "./SwitchButton";

/**
 * Binding of one Switch button: a chord of up to [`CHORD_MAX`] codes; empty means nothing.
 */
export type Binding = { 
/**
 * Switch button.
 */
button: SwitchButton, 
/**
 * Codes: for the keyboard, a VK code or a mouse action from [`MOUSE_CODE_FIRST`]; for the controller,
 * a target number 1…[`PAD_TARGET_COUNT`].
 */
codes: Array<number>, };
