// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandError } from "./CommandError";
import type { GameSummary } from "./GameSummary";

/**
 * Build result.
 */
export type BuildFinished = { 
/**
 * Tile of the built game.
 */
game: GameSummary | null, 
/**
 * The error, if the build failed.
 */
error: CommandError | null, };
