// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildStage } from "./BuildStage";

/**
 * Build progress.
 */
export type BuildProgress = { 
/**
 * Current stage.
 */
stage: BuildStage, 
/**
 * Stage completion, 0…100.
 */
percent: number, 
/**
 * Log line.
 */
log: string | null, };
