// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutorunSettings } from "./AutorunSettings";
import type { GameSource } from "./GameSource";
import type { Metadata } from "./Metadata";
import type { TitleId } from "./TitleId";

/**
 * What the window submits for a build.
 */
export type BuildRequest = { 
/**
 * Title ID of the game being rebuilt; `None` means a new game.
 */
titleId: TitleId | null, 
/**
 * What to build from.
 */
source: GameSource, 
/**
 * Metadata.
 */
metadata: Metadata, 
/**
 * Autorun settings.
 */
settings: AutorunSettings, 
/**
 * Icon the window made from the chosen source; `None` means the default runtime icon.
 */
icon: number[] | null, };
