// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutorunSettings } from "./AutorunSettings";
import type { GameSource } from "./GameSource";
import type { Metadata } from "./Metadata";
import type { TitleId } from "./TitleId";

/**
 * Everything the NSP was built from: the contents of `carafe.json` inside it.
 *
 * A full snapshot: changing the app's general settings does not affect a built game.
 */
export type BuildRecord = { 
/**
 * File format version.
 */
formatVersion: number, 
/**
 * Title ID, permanent for the game.
 */
titleId: TitleId, 
/**
 * Build number of this game, starting from 1.
 */
buildNumber: number, 
/**
 * Carafe runtime version the NSP was built with.
 */
runtimeVersion: string, 
/**
 * Where the game was built from.
 */
source: GameSource, 
/**
 * NSP metadata.
 */
metadata: Metadata, 
/**
 * Autorun settings.
 */
settings: AutorunSettings, };
