// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * A command error: a code for translation and a text for the log.
 */
export type CommandError = { 
/**
 * Kind of error.
 */
code: ErrorCode, 
/**
 * Details for the log.
 */
message: string, };
