// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Crop square in pixels of the source image.
 */
export type Crop = { 
/**
 * Left edge.
 */
x: number, 
/**
 * Top edge.
 */
y: number, 
/**
 * Side of the square.
 */
size: number, };
