// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Switch connection.
 */
export type DeviceStatus = { 
/**
 * The Switch is visible over MTP.
 */
connected: boolean, 
/**
 * What it is visible through, for example "MTP".
 */
via: string | null, };
