// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of error; the window uses it to pick the text from the translations.
 */
export type ErrorCode = "notFound" | "io" | "pack" | "blocked" | "noSpace" | "pathTooLong" | "runtimeDamaged" | "device" | "network" | "apiKey" | "unsupported" | "invalid" | "busy";
