// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutableInfo } from "./ExecutableInfo";
import type { ExecutableKind } from "./ExecutableKind";

/**
 * An `.exe` in the wizard list.
 */
export type ExecutableChoice = { 
/**
 * Information about the file.
 */
info: ExecutableInfo, 
/**
 * Game or installer.
 */
kind: ExecutableKind, };
