// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an `.exe` looks like the game itself or like an installer.
 */
export type ExecutableKind = "game" | "installer";
