// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arch } from "./Arch";

/**
 * Executable in the game folder.
 */
export type ExecutableInfo = { 
/**
 * Path relative to the game folder.
 */
path: string, 
/**
 * Bitness from the PE header.
 */
arch: Arch, 
/**
 * The `.exe` runs only at its own address below 4 GB: it gets a 32-bit address space.
 */
fixedAddress: boolean, 
/**
 * Size in bytes.
 */
sizeBytes: number, 
/**
 * `ProductName` from the version resource.
 */
productName: string | null, 
/**
 * `CompanyName` from the version resource.
 */
companyName: string | null, };
