// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A web page the window may ask to open.
 */
export type ExternalLink = "source" | "license";
