// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutableInfo } from "./ExecutableInfo";

/**
 * What was found in the game folder.
 */
export type FolderReport = { 
/**
 * Game folder.
 */
folder: string, 
/**
 * `.exe` files for x86 and x86-64 in the folder and subfolders.
 */
executables: Array<ExecutableInfo>, 
/**
 * There is a `steam_api.dll` or `steam_api64.dll`.
 */
hasSteamApi: boolean, };
