// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arch } from "./Arch";

/**
 * Where the game was built from on the PC.
 */
export type GameSource = { 
/**
 * Game folder.
 */
folder: string, 
/**
 * Path to the `.exe` relative to the folder.
 */
executable: string, 
/**
 * Bitness of the `.exe`.
 */
arch: Arch, 
/**
 * Launch arguments.
 */
arguments: Array<string>, };
