// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arch } from "./Arch";
import type { TitleId } from "./TitleId";

/**
 * Library tile.
 */
export type GameSummary = { 
/**
 * Title ID.
 */
titleId: TitleId, 
/**
 * Title.
 */
title: string, 
/**
 * Publisher.
 */
publisher: string, 
/**
 * Version for display.
 */
version: string, 
/**
 * Bitness of the `.exe`.
 */
arch: Arch, 
/**
 * NSP size in bytes.
 */
sizeBytes: number, 
/**
 * Icon as a `data:` URL.
 */
icon: string | null, 
/**
 * Runtime version the NSP was built with.
 */
runtimeVersion: string, 
/**
 * The runtime in Carafe is newer than in the NSP.
 */
runtimeOutdated: boolean, };
