// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direct3d } from "./Direct3d";
import type { DxvkHud } from "./DxvkHud";
import type { DxvkSource } from "./DxvkSource";
import type { LsfgFlow } from "./LsfgFlow";
import type { Upscaling } from "./Upscaling";

/**
 * Image output.
 */
export type GraphicsSettings = { 
/**
 * What renders Direct3D.
 */
direct3d: Direct3d, 
/**
 * DXVK build.
 */
dxvkSource: DxvkSource, 
/**
 * Frame limit from [`FRAME_LIMITS`]; `0` means no limit.
 */
frameLimit: number, 
/**
 * Vertical sync.
 */
vsync: boolean, 
/**
 * Scaling.
 */
upscaling: Upscaling, 
/**
 * FSR sharpness in percent: 0, 20, …, 100.
 */
sharpness: number, 
/**
 * DXVK HUD.
 */
hud: DxvkHud, 
/**
 * LSFG-VK frame generation.
 */
lsfg: boolean, 
/**
 * LSFG-VK in performance mode.
 */
lsfgPerformance: boolean, 
/**
 * LSFG-VK optical flow scale.
 */
lsfgFlow: LsfgFlow, };
