// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crop } from "./Crop";

/**
 * Where the 256×256 icon comes from.
 */
export type IconSource = { "kind": "executable" } | { "kind": "file", 
/**
 * Path to the image on the PC.
 */
path: string, 
/**
 * Crop square.
 */
crop: Crop, } | { "kind": "steamGridDb", 
/**
 * Game on SteamGridDB.
 */
gameId: number, 
/**
 * Cover on SteamGridDB.
 */
imageId: number, 
/**
 * URL of the full-size cover.
 */
url: string, 
/**
 * Crop square.
 */
crop: Crop, };
