// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Binding } from "./Binding";
import type { InputMode } from "./InputMode";

/**
 * Input: mode, dead zones and two mappings.
 */
export type InputSettings = { 
/**
 * Input mode.
 */
mode: InputMode, 
/**
 * Left stick dead zone, 0…25.
 */
leftDeadzone: number, 
/**
 * Right stick dead zone, 0…25.
 */
rightDeadzone: number, 
/**
 * Show the on-screen keyboard automatically.
 */
keyboardAuto: boolean, 
/**
 * Mapping for the "keyboard and mouse" mode: all 24 buttons.
 */
keys: Array<Binding>, 
/**
 * Mapping for the controller mode: all 24 buttons.
 */
pad: Array<Binding>, };
