// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandError } from "./CommandError";
import type { TitleId } from "./TitleId";
import type { TransferProgress } from "./TransferProgress";

/**
 * Installation progress of one game.
 */
export type InstallEvent = { 
/**
 * The game being installed.
 */
titleId: TitleId, 
/**
 * How much has been transferred.
 */
progress: TransferProgress | null, 
/**
 * The error, if the installation failed.
 */
error: CommandError | null, };
