// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the required keys were found in `prod.keys`.
 */
export type KeysReport = { 
/**
 * `header_key` was found.
 */
headerKey: boolean, 
/**
 * `key_area_key_application_00` was found.
 */
keyAreaKey: boolean, };
