// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NacpLanguage } from "./NacpLanguage";

/**
 * Title and publisher for one system language, replacing the main ones.
 */
export type LocalizedTitle = { 
/**
 * Switch system language.
 */
language: NacpLanguage, 
/**
 * Title for this language.
 */
title: string, 
/**
 * Publisher for this language; `None` means the main one.
 */
publisher: string | null, };
