// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IconSource } from "./IconSource";
import type { LocalizedTitle } from "./LocalizedTitle";

/**
 * NSP metadata visible on the Switch.
 */
export type Metadata = { 
/**
 * Title for all languages.
 */
title: string, 
/**
 * Publisher for all languages.
 */
publisher: string, 
/**
 * Title and publisher overrides for individual languages.
 */
localized: Array<LocalizedTitle>, 
/**
 * Version for display; `None` means the build number.
 */
displayVersion: string | null, 
/**
 * Icon source.
 */
icon: IconSource, };
