// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Switch system language: one of the 16 title entries in the NACP.
 */
export type NacpLanguage = "americanEnglish" | "britishEnglish" | "japanese" | "french" | "german" | "latinAmericanSpanish" | "spanish" | "italian" | "dutch" | "canadianFrench" | "portuguese" | "russian" | "korean" | "traditionalChinese" | "simplifiedChinese" | "brazilianPortuguese";
