// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutorunSettings } from "./AutorunSettings";
import type { Language } from "./Language";
import type { Theme } from "./Theme";
import type { UpdateMode } from "./UpdateMode";

/**
 * Application settings.
 */
export type Preferences = { 
/**
 * Onboarding is complete.
 */
onboarded: boolean, 
/**
 * Interface language.
 */
language: Language, 
/**
 * Interface theme.
 */
theme: Theme, 
/**
 * Path to `prod.keys`.
 */
keysPath: string | null, 
/**
 * Library folder.
 */
libraryDir: string | null, 
/**
 * Autorun settings for new games.
 */
defaults: AutorunSettings, 
/**
 * SteamGridDB API key for cover search.
 */
steamGridDbKey: string | null, 
/**
 * How Carafe looks for its new versions.
 */
updates: UpdateMode, 
/**
 * The version the player chose not to be told about.
 */
skippedUpdate: string | null, 
/**
 * The runtime version for which the player chose not to be offered a rebuild.
 */
rebuildDismissed: string | null, };
