// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutorunSettings } from "./AutorunSettings";
import type { Language } from "./Language";
import type { Theme } from "./Theme";

/**
 * Application settings.
 */
export type Preferences = { 
/**
 * Onboarding is complete.
 */
onboarded: boolean, 
/**
 * Interface language.
 */
language: Language, 
/**
 * Interface theme.
 */
theme: Theme, 
/**
 * Path to `prod.keys`.
 */
keysPath: string | null, 
/**
 * Library folder.
 */
libraryDir: string | null, 
/**
 * Autorun settings for new games.
 */
defaults: AutorunSettings, 
/**
 * SteamGridDB API key for cover search.
 */
steamGridDbKey: string | null, };
