// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebuildItemState } from "./RebuildItemState";
import type { TitleId } from "./TitleId";

/**
 * One game of the rebuild.
 */
export type RebuildItem = { 
/**
 * The game.
 */
titleId: TitleId, 
/**
 * Its title.
 */
title: string, 
/**
 * Where it stands.
 */
state: RebuildItemState, };
