// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebuildItem } from "./RebuildItem";

/**
 * The rebuild of several games.
 */
export type RebuildStatus = { 
/**
 * The games in build order; empty if no rebuild was started.
 */
items: Array<RebuildItem>, 
/**
 * A game is being built or waits for its turn.
 */
running: boolean, 
/**
 * The player asked to stop after the current game.
 */
stopping: boolean, };
