// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TitleId } from "./TitleId";

/**
 * The library's offer to rebuild games made with an older runtime.
 */
export type RebuildOffer = { 
/**
 * The runtime version in Carafe.
 */
runtimeVersion: string, 
/**
 * Games made with an older runtime, in library order.
 */
games: Array<TitleId>, 
/**
 * The player chose not to be offered a rebuild for this runtime.
 */
dismissed: boolean, };
