// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildStage } from "./BuildStage";
import type { CommandError } from "./CommandError";

/**
 * Where one game of the rebuild stands.
 */
export type RebuildItemState = { "state": "waiting" } | { "state": "building", 
/**
 * Current stage.
 */
stage: BuildStage, 
/**
 * Stage completion, 0…100.
 */
percent: number, } | { "state": "done" } | { "state": "failed", 
/**
 * Why.
 */
error: CommandError, } | { "state": "skipped" };
