// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Carafe release newer than the running one.
 */
export type Release = { 
/**
 * Version of the release.
 */
version: string, 
/**
 * The release carries a runtime newer than the running one: games are worth rebuilding.
 */
runtimeChanged: boolean, 
/**
 * Size of the installer in bytes, if the release states it.
 */
sizeBytes: number | null, };
