// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildRecord } from "./BuildRecord";

/**
 * NSP in the library folder.
 */
export type StoredGame = { 
/**
 * Record from `carafe.json` inside the NSP.
 */
record: BuildRecord, 
/**
 * NSP file name.
 */
fileName: string, 
/**
 * NSP size in bytes.
 */
sizeBytes: number, 
/**
 * Icon as a `data:` URL, if it could be read.
 */
icon: string | null, };
