// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Switch button or stick direction: a source in the Autorun mapping.
 */
export type SwitchButton = "A" | "B" | "X" | "Y" | "L" | "R" | "ZL" | "ZR" | "PLUS" | "MINUS" | "STICKL" | "STICKR" | "UP" | "DOWN" | "LEFT" | "RIGHT" | "LUP" | "LDOWN" | "LLEFT" | "LRIGHT" | "RUP" | "RDOWN" | "RLEFT" | "RRIGHT";
