// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuEmulator } from "./CpuEmulator";
import type { SyncMode } from "./SyncMode";
import type { WindowOutput } from "./WindowOutput";

/**
 * CPU, synchronization, windows.
 */
export type SystemSettings = { 
/**
 * Thread synchronization mode.
 */
sync: SyncMode, 
/**
 * CPU emulator.
 */
cpu: CpuEmulator, 
/**
 * Give the game four cores.
 */
fourCores: boolean, 
/**
 * Where windows are output.
 */
windows: WindowOutput, };
