// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Switch application identifier following the Carafe rule: `0x05XXXXXXXXXX[02468ace]000`.
 *
 * The high byte is `0x05`, the fourth hex digit from the end is even, the three lowest are zeros.
 * As long as the Title ID stays the same, reinstalling over the game keeps its save data.
 */
export type TitleId = string;
