// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of a transfer to the Switch.
 */
export type TransferProgress = { 
/**
 * Bytes transferred.
 */
doneBytes: number, 
/**
 * Total bytes.
 */
totalBytes: number, };
