// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailedStep } from "./FailedStep";
import type { Release } from "./Release";

/**
 * Where the update of Carafe stands.
 */
export type UpdateState = { "state": "idle" } | { "state": "available", 
/**
 * The release.
 */
release: Release, } | { "state": "downloading", 
/**
 * The release.
 */
release: Release, 
/**
 * Bytes received so far.
 */
received: number, 
/**
 * Size of the installer, if the server reported it.
 */
total: number | null, } | { "state": "ready", 
/**
 * The release.
 */
release: Release, } | { "state": "failed", 
/**
 * The release.
 */
release: Release, 
/**
 * Where it stopped.
 */
step: FailedStep, };
