// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How Carafe looks for new versions on its own.
 */
export type UpdateMode = "automatic" | "notifyOnly" | "off";
