// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateState } from "./UpdateState";

/**
 * What the window knows about updating Carafe.
 */
export type UpdateStatus = { 
/**
 * This build can update itself; development builds cannot.
 */
enabled: boolean, 
/**
 * Where the update stands.
 */
state: UpdateState, 
/**
 * A build or a USB install is running: installing now would interrupt it.
 */
busy: boolean, 
/**
 * The update is installed when Carafe closes.
 */
installOnClose: boolean, 
/**
 * The update is installed, and Carafe restarts, as soon as the running work finishes.
 */
installWhenIdle: boolean, 
/**
 * When the last check finished, in milliseconds since the Unix epoch.
 */
checkedAt: number | null, 
/**
 * The version Carafe was updated to before this start.
 */
updatedTo: string | null, };
