// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scaling of the frame to the screen.
 */
export type Upscaling = "off" | "fsr" | "integer";
