// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wizard warning. Does not prevent the build.
 */
export type Warning = "unstableX64" | "steamApi" | "installerSelected" | "onlyInstallers" | "x86OnX64" | "x64OnFixedAddress";
