// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the game windows are output.
 */
export type WindowOutput = "auto" | "framebuffer" | "compositor";
