// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutableChoice } from "./ExecutableChoice";
import type { Metadata } from "./Metadata";

/**
 * Initial wizard state after the folder is chosen.
 */
export type WizardDraft = { 
/**
 * Game folder.
 */
folder: string, 
/**
 * `.exe` files: games first by descending size, then installers.
 */
executables: Array<ExecutableChoice>, 
/**
 * The `.exe` selected by default; `None` if the folder has only installers.
 */
selected: string | null, 
/**
 * Default metadata.
 */
metadata: Metadata, 
/**
 * The folder has `steam_api.dll`.
 */
hasSteamApi: boolean, };
